apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-todo-app
  labels:
    app: todo-app
  name: todo-app
  namespace: argocd-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: kotisaiaravind/todo_app:latest
